### PR TITLE
Add support for hash filter values. 

### PR DESCRIPTION
**Pull request by shirish-pampoorickal**
When a hash is passed in as a filter value, it gets striingified as shown below:
```
  presenter.extract_filters({ 'owned_by' => { :ids => [2], 2 => [1] }}

  returns "{ 'owned_by' => { :ids => [2], 2 => [1] }"
```

This PR fixes the issue with passing in a hash value for a filter & returns a hash rather a stringified version of the hash

### CODE REVIEW

**Comment by shirish-pampoorickal** [comment]
@naganowl / @jrolfs Appreciate a look

**Comment by juanca** [comment]
LGTM! Thanks @shirish-pampoorickal!

**Comment by jrolfs** [comment]
Looks great, thanks @shirish-pampoorickal!

**Comment by cantino** [comment]
Just be sure that whatever method you're passing user data to sanitizes it and doesn't assume it's a string / integer. ;)

**Comment by shirish-pampoorickal** [comment]
@cantino 👍

**Pull request merged**
