### PR TITLE
Brainstem V2 & the Presenter DSL [Work In Progress]

### PR DESCRIPTION
**Pull request by cantino**
Goal:

Convert Brainstem to use a class-level DSL for building presenters.  This should enable automatic documentation generation, smarter preloading and caching, and better handling of polymorphic associations.

Here is an example: https://github.com/mavenlink/brainstem/blob/presenter_dsl/spec/spec_helpers/presenters.rb

TODO:

- [x] Create an inheritable DSL
- [x] Handle associations
- [x] Handle fields
- [x] Handle conditionals
- [x] Update how helpers are managed
- [x] Helpers should inherit
- [x] Use strings everywhere
- [x] Do not run associations twice
- [x] Move `perform_preloading` into `group_present`.
- [x] Pull filters and sorts into the DSL and use the new helpers.
- [x] Support the new helpers in filters and sorts
- [x] Implement `preload` DSL
- [x] use the PresenterValidator
- [x] Evaluate "Why don’t we have the presenters just know the brainstem_key for all models, then we can ask the presenter collection where any given model type should go?"

To document:

- [x] `present_objects` is now `brainstem_present_objects` and `present` is now `brainstem_present`
- [x] `brainstem_keys` are no longer auto-pluralized.  Please check your presenters.
- [x] removal of `key_map` and addition of `brainstem_key`
- [x] `options[:as]` is now `options[:brainstem_key]`
- [x] new `helper` syntax and exposure
- [x] new `PresenterCollection#validate!` method
- [x] Use of `Rails.application.config.to_prepare` for eager loading.

Future work:

- handle polymorphism in `PresenterCollection` 
- Allow extra data to be passed from controller to presenter
- Handle optional fields

### CODE REVIEW

**Comment by cantino** [comment]
@shirish-pampoorickal @naiyt You may find these efforts interesting.

**Comment by naiyt** [comment]
Awesome! I'll have to read through this.

**Comment by cantino** [comment]
Testing presenters in an app:

```ruby
describe Api::V1::StoryStateChangePresenter do
  it_should_behave_like "a v1 api presenter", described_class
  ...

shared_examples_for "a v1 api presenter" do |presenter_class, presentation_lambda|
  it 'passes Brainstem::PresenterValidator' do
    validator = Brainstem::PresenterValidator.new(presenter_class)
    validator.valid?
    validator.should be_valid, "expected a valid presenter, got: #{validator.errors.full_messages}"
  end
end
```

**Comment by cantino** [comment]
@naiyt And this.

**Comment by cantino** [comment]
Well, I think this is ready to get merged into master!

**Pull request merged**
