### PR TITLE
Refactor structuring JSON response into own method for reusability

### PR DESCRIPTION
**Pull request by juanca**
Useful for preloading data in an ERB partial

TODO
-

- [x] Check spec coverage

@cantino @rogerneel

### CODE REVIEW

**Comment by juanca** [comment]
@ahuth @bgreg

**Comment by juanca** [comment]
Added some sanity specs to ensure method is actually structuring the data. Pre-existing specs seem to already be covering its actual functionality.

**Comment by juanca** [comment]
@shirish-pampoorickal whatcha think?

**Comment by bennapp** [comment]
@juanca LGTM! :beers:

**Comment by juanca** [comment]
Gracias!

**Comment by shirish-pampoorickal** [comment]
Looks good @juanca :+1:

**Pull request merged**
